### ISSUE TITLE
[feature request] Add streaming support for query results

### ISSUE THREAD

**Issue by thomasdziedzic** [propertybase/executrix#24]
For really large data sets, it would be nice to be able to pass in a block to the query method and have it return a batch of csv rows to process before continuing on with the rest of the results.

e.g. If I want to query over 500,000 records with all of their fields, it can easily overwhelm the memory usage on my computer.

**Comment by leifg** [comment]
@theSteveMitchell I guess that is what you implemented in #19 right? Is the gem you mentioned open source yet?

**Comment by theSteveMitchell** [comment]
Yes with #19 I got file streaming working.  For me there were just a lot of problems with correctly parsing text fields that might contain newlines, special characters, etc.  But for cleaner data that should work.

sf-bulk-api is not on the public github yet, but it does handle this case much better, and I'll try to get that out this week or next.

**Comment by gostrc** [comment]
@theSteveMitchell why did you have to create an entirely new gem for the salesforce bulk api? Are the internals of executrix not flexible enough to support streaming?

**Comment by theSteveMitchell** [comment]
I didn't create a new one.  I discovered an internal gem my company has created, that already solved the problem with streaming data, as well as parsing.  I'm trying to get that gem published publicly.

**Comment by gostrc** [comment]
ah ok, thanks for the explanation

**Comment by leifg** [comment]
I moved this gem over to [bulkforce](https://github.com/propertybase/bulkforce). I want to implement communication with the API via XML. Streaming should be simpler there.

Can you open the issue there?
